plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

version = "${project.mod_version}+${project.minecraft_version}"
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    maven { url = "https://maven.terraformersmc.com/releases/" }
    maven { url = "https://maven.fzzyhmstrs.me/" }
    maven { url = "https://maven.ladysnake.org/releases" }
    maven {
        url = "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven { url = "https://maven.blamejared.com/" }
}

loom {
    accessWidenerPath = file("src/main/resources/easy_villagers.accesswidener")
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    implementation "com.terraformersmc:modmenu:18.0.0-alpha.8"
    implementation "me.fzzyhmstrs:fzzy_config:${project.fzzy_config_version}"

    compileOnly("curse.maven:jade-324717:${project.jade_version}")
    runtimeOnly("curse.maven:jade-324717:${project.jade_version}")
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": inputs.properties.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
    options.compilerArgs += ["-Xlint:all"]
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    def archiveName = base.archivesName.get()
    from("LICENSE") {
        rename { "${it}_${archiveName}" }
    }
}
dependencies { compileOnly files('C:/MCServer/MCMods/TechUpdate/TechReborn-26.1/RebornCore/build/libs/RebornCore-6.0.5+local.jar') }
