org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

java_version=25
java_toolchain_version=25

mod_loader=neoforge
minecraft_version=26.1.2
minecraft_dependency=[26.1,26.2)
neoforge_version=26.1.2.1-beta
neoforge_dependency=[26.1.0.1-beta,)
corelib_version=2.1.12

jei_version=29.2.0.20
jade_version=26.0.6+neoforge

# Mod information
mod_version=1.1.42+26.1.2
mod_id=easy_villagers
mod_display_name=Easy Villagers

# Script configuration
enable_accesstransformers=true

# Project upload
curseforge_upload_minecraft_versions=26.1, 26.1.1, 26.1.2
modrinth_upload_supported_game_versions=26.1, 26.1.1, 26.1.2
curseforge_upload_id=400514
modrinth_upload_id=Kaov2qgi
upload_release_type=beta
upload_recommended=true

curseforge_upload_optional_dependencies=jei, jade
modrinth_upload_optional_dependencies=jei, jade

# Gradle plugins
mod_gradle_script_version=1.0.60
moddevgradle_version=2.0.+
mod_update_version=2.0.0
cursegradle_version=1.5.1
shadow_version=9.4.0
minotaur_version=2.+
