# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache
org.gradle.configuration-cache=false

java_version=25
java_toolchain_version=25

# Fabric Properties
minecraft_version=26.1.2
loader_version=0.19.2
loom_version=1.16-SNAPSHOT
fabric_version=0.145.1+26.1
jade_version=8048381
jei_version=29.5.0.28
fzzy_config_version=0.7.6+26.1-pre-3

# Mod Properties
mod_version=1.1.42
maven_group=de.maxhenkel.easyvillagers
archives_base_name=easy-villagers
